#Theoratical Questions:

In [ ]:
#Question1: Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?



1.   NumPy is an indispensable tool for scientific computing, data analysis, and numerical computations in Python. Its ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries solidifies its position as the cornerstone of numerical computing in Python.
2.   It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.






In [ ]:
#Question2: Compare and contrast np.mean() and np.average() function in NumPY. When would you use one over the other?




1.   np.mean():  
In numpy library, np.mean() is a function used to calculate arithmetic mean of the given array along with the axis.
2.   np.average():  
The arithmetic mean and weighted average calculations are more flexible with np.average(). It can calculate the weighted average if we pass the weigh



In [ ]:
# Example of np.mean()
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array : ",arr,"\n")
print("Mean of the Array : ",np.mean(arr))

Array :  [ 1  2  3  4  5  6  7  8  9 10] 

Mean of the Array :  5.5


In [ ]:
# Example of np.average()
import numpy as np
weight = np.array([4,5,6,12,15,10,2,8,19,20])
print("Weight average of Array : ",np.average(arr, weights=weight))

Weight average of Array :  6.574257425742574


In [ ]:
#Question3: Describe the method for reversing a NumPy array along different axes. Provide examples for 1D ad 2D array.



1.   In NumPy  reversing method are np.flip() are used to reverse the axis in numpy array.



In [ ]:
# Example of 1D array
l = ["ajay",2,3,4,5]
arr = np.array(l)

In [ ]:
arr

array(['ajay', '2', '3', '4', '5'], dtype='<U21')

In [ ]:
arr.ndim

1

In [ ]:
#Example of 2D array
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.ndim

2

In [ ]:
# Question4: How can you determine the data type of elements in a NumPy array? Discus the importance of data types in memory manegment and performance.



#Data type of element in a NumPy array are
*   dtype = int

*   dtype = float
*   In NumPy data type by defalt all the array values is in float.





In [ ]:
# Taking an example of data type
import numpy as np
arr = np.zeros(5)

In [ ]:
arr  #by defalt numpy array takes values in float

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros(5, dtype = int) # changing this value as int
arr

array([0, 0, 0, 0, 0])

In [ ]:
#Question5: Define ndarrays in NumPy and explain their key features. How do they differ from standered python lists?

#ndarray is defined as N-dimensional array(ndarray) in python.

*   An ndarray is a multi-dimensional array of items of the same type and size. The number of dimensions and items contained in the array is defined with a tuple of N non-negative integers that specify each dimension's size. An ndarray has an associated data type object which specify the dtype stored in the array.




In [ ]:
import numpy as np

# Creating array object
arr = np.array([[1, 2, 3],
                [4, 2, 5]])

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [ ]:
# Question 6: Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.



1.   Performance:   NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are implemented in C, resulting in faster performance than equivalent operations on lists.
2.   Performance: Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead. They are generally used as general-purpose data structures



In [ ]:
# Question7: Compare vstack()and hstack() function in numpy. Provide example demonstrating their usage and output.



1.   numpy.hstack() in Python:  
numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.
2.   numpy.vstack() in python:  
numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.





In [ ]:
#Example of hstack function in numpy
import numpy as np

# input array
arr1 =np.array([ 1, 2, 3] )
print ("1st Input array : \n", arr1)

arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", arr2)

# Stacking the two arrays horizontally
out_arr = np.hstack((arr1, arr2))
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [ ]:
#Example of vstack function in numpy
import numpy as np

# input array
arr1 =np.array([ 1, 2, 3] )
print ("1st Input array : \n", arr1)

arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", arr2)

# Stacking the two arrays vertically
out_arr = np.vstack((arr1, arr2))
print ("Output vertically stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [ ]:
# Question8: Explain the difference between fliplr() and flipud() method in NumPy, including their effects on various arrary dimensions.



1.   fliplr(array) : Flip array(entries in each column) in left-right direction, shape preserved
2.   flipud() function flips the array(entries in each column) in up-down direction, shape preserved



In [ ]:
# This is example of fliplr()
import numpy as np

array = np.arange(8).reshape((2,2,2))
print("Original array : \n", array)

# fliplr : means flip left-right
print("\nFlipped array left-right : \n", np.fliplr(array))

Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Flipped array left-right : 
 [[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]


In [ ]:
# This is example of flipud()
import numpy as np

array = np.arange(8).reshape((2,2,2))
print("Original array : \n", array)

# flipud : means flip up-down
print("\nFlipped array : \n", np.flipud(array))

Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Flipped array : 
 [[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]


In [ ]:
# Question9: Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?



*  array_split() s plitting into equal or nearly equal sub-arrays or is similar to numpy. split()
*   Array splitting in NumPy is like a slice of cake. Think of each element in a NumPy array as a slice of cake. Splitting divides this “cake” into smaller “slices” (sub-arrays), often along specific dimensions or based on certain criteria. We can split horizontally, vertically, or even diagonally depending on our needs.

The split(), hsplit(), vsplit(), and dsplit() functions are important tools for dividing arrays along various axes and dimensions. These functions are particularly useful when working with one-dimensional arrays, matrices, or high-dimensional datasets



In [ ]:
import numpy as np

# Creating an example array
array = np.arange(13)

# Splitting the array into 4 unequal parts along the first axis (axis=0)
result = np.array_split(array, 4)

print("Array:")
print(array)
print("\nResult after numpy.array_split():")
print(result)

Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

Result after numpy.array_split():
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [ ]:
# Question10: Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#VECTORIZATION IN NUMPY:

1.  Vectorization is the process of converting an algorithm from operating on a single value at a time to operating on a set of values (vector) at one time.

*   These techniques to perform operations on Numpy arrays without using loops. It only uses the pre-defined inbuilt functions like the sum function etc., and mathematical operations like "+", "-", "/" etc. for performing operations in Numpy arrays.

#BROADCASTING IN NUMPY:

2. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.  

Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. This is because NumPy is implemented in C Programming, which is a very efficient language. It does this without making needless copies of data which leads to efficient algorithm implementations.

##PRACTICAL QUESTIONS:

In [ ]:
# Question1: Create a 3*3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
arr = np.random.randint(1,100,(3,3))

In [ ]:
arr

array([[96, 51, 89],
       [57, 44,  8],
       [63, 88, 78]])

In [ ]:
arr.reshape(3,3,1)

array([[[96],
        [51],
        [89]],

       [[57],
        [44],
        [ 8]],

       [[63],
        [88],
        [78]]])

In [ ]:
# Questio2: Generate a 1D NumPy with 10 elements. Reshape it into a 2*5 array, then into 5*2 array.

In [ ]:
import numpy as np
# 1-D array having elements [1 2 3 4 5 6 7 8 9 10]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Now we can convert this 1-D array into 2-D in two ways

# 1. having dimension 5 x 2
arr1 = arr.reshape(5, 2)
print ('After reshaping having dimension 5x2:')
print (arr1)
print ('\n')

# 2. having dimension 2 x 5
arr2 = arr.reshape(2, 5)
print ('After reshaping having dimension 2x5:')
print (arr2)
print ('\n')

After reshaping having dimension 5x2:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


After reshaping having dimension 2x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]




In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# Questio3: Create a 4*4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6*6 array.

In [ ]:
import numpy as np
arr=np.ones((4,4))
print("Array arr is :\n",arr)
arr1=np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Border of 0 around array arr :\n",arr1)


Array arr is :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Border of 0 around array arr :
 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# Questio4: Using numpy create an array of integers from 10 to 60 with a step of 5.

In [ ]:
arr = np.arange(10, 60, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
# Question5: Create a numpy array of strings ['python', 'numpy', 'pandas'] apply different case transformation(uppercase, lowercase, titlecase, etc) to each element.

In [ ]:
import numpy as np

# Creating a NumPy array containing strings
x = np.array(["python", "numpy", "pandas"])

# Displaying the original array
print("Original Array:")
print(x)

# Converting all characters to lowercase
lowered_case = np.char.lower(x)

# Converting all characters to uppercase
uppered_case = np.char.upper(x)

# Capitalizing the first character of each word in the string
titlecased_case = np.char.title(x)

print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Titlecased: ", titlecased_case)


Original Array:
['python' 'numpy' 'pandas']
Lowered:  ['python' 'numpy' 'pandas']
Uppered:  ['PYTHON' 'NUMPY' 'PANDAS']
Titlecased:  ['Python' 'Numpy' 'Pandas']


In [ ]:
# Question6: Generate a numpy array of words insert a space between each charecter of every word in the array.

In [ ]:

# importing numpy as np
import numpy as np


# creating array of string
arr = np.array(["Physics", "Wallah","offers", "varities", "of", "Programs", "to", "helps", "students"])


print("Printing the Original Array:")
print(arr)

# inserting space using np.char.join()
r = np.char.join(" ", arr)
print("Printing the array after inserting space\between the elements")

print(r)

Printing the Original Array:
['Physics' 'Wallah' 'offers' 'varities' 'of' 'Programs' 'to' 'helps'
 'students']
Printing the array after inserting spaceetween the elements
['P h y s i c s' 'W a l l a h' 'o f f e r s' 'v a r i t i e s' 'o f'
 'P r o g r a m s' 't o' 'h e l p s' 's t u d e n t s']


In [ ]:
# Question7: Create two 2D numpy array and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [ ]:
arr1,arr2

(array([[2, 1, 2],
        [2, 2, 2],
        [1, 2, 1]]),
 array([[1, 2, 1],
        [1, 1, 1],
        [1, 1, 1]]))

In [ ]:
arr1+arr2

array([[3, 3, 3],
       [3, 3, 3],
       [2, 3, 2]])

In [ ]:
arr1-arr2

array([[ 1, -1,  1],
       [ 1,  1,  1],
       [ 0,  1,  0]])

In [ ]:
arr1*arr2

array([[2, 2, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [ ]:
arr1/arr2

array([[2. , 0.5, 2. ],
       [2. , 2. , 2. ],
       [1. , 2. , 1. ]])

In [ ]:
# Question8: Use numpy to create a 5*5 identity Matrix then extract its diagonal element

In [ ]:
import numpy as np
arr = np.arange(25).reshape((5, 5))
print("Original element:")
print(arr)
print("Diagonal element:")
print(np.diag(arr))



Original element:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Diagonal element:
[ 0  6 12 18 24]


In [ ]:
# Question9: Generate a numpy array of 100 random integer between 0 and 1000. Find and display all prime number in this array.

In [ ]:
import numpy as np
import math

def is_prime(n):
    if n % 2 == 0 and n > 2:
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))

a = np.arange(1, 1000)
foo = np.vectorize(is_prime)
pbools = foo(a)
primes = np.extract(pbools, a)
primes  # => Output below


array([  1,   2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,
        41,  43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97,
       101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163,
       167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233,
       239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311,
       313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389,
       397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463,
       467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563,
       569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641,
       643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727,
       733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821,
       823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907,
       911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997])

In [ ]:
# Question10: Create a NumPy array representing daily temperature for a month calculate and display the weekly averages.

In [12]:
!git push -u origin main

fatal: not a git repository (or any of the parent directories): .git
